---
- name: Install Docker related OS packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
- name: Add Docker's official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Add Docker repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
    state: present
- name: Install Docker CE
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
- name: Install Docker compose
  apt:
    name: docker-compose
    state: latest
