---
- name: Prepare web directory
  file:
    dest: '{{ deploydest }}'
    state: directory
    owner: '{{ pyconusr }}'
    group: '{{ pycongrp }}'
    mode: 0755
- name: Clone web repository
  git:
    repo: '{{ gitrepos }}'
    dest: '{{ deploydest }}/pyconjp-{{ pyconyear }}'
    force: yes
  become: True
  become_user: '{{ pyconusr }}'
- name: Rewrite docker-compose.yml
  replace:
    path: '{{ deploydest }}/pyconjp-{{ pyconyear }}/docker-compose.yml'
    regexp: '- GIT_BRANCH=dev'
    replace: '- GIT_BRANCH={{ deploybranch }}'
  become: True
  become_user: '{{ pyconusr }}'
- name: Start web service
  shell: docker-compose up -d
  args:
    chdir: '{{ deploydest }}/pyconjp-{{ pyconyear }}'
  become: True
  become_user: '{{ pyconusr }}'
- name: Copy update-web script
  copy:
    src: '{{ role_path }}/files/update-web.sh'
    dest: '{{ deploydest }}/update-web.sh'
    mode: 0755
    owner: '{{ pyconusr }}'
    group: '{{ pycongrp }}'
- name: Setup crontab
  cron:
    name: update-web
    cron_file: /etc/crontab
    minute: 0
    hour: 4
    day: '*'
    month: '*'
    weekday: '*'
    user: '{{ pyconusr }}'
    job: '{{ deploydest }}/update-web.sh >/dev/null 2>&1'
