---
- name: Prepare web directory
  file:
    dest: '{{ deploydest }}'
    state: directory
    owner: '{{ pyconusr }}'
    group: '{{ pycongrp }}'
    mode: 0755
- name: Clone web repository
  git:
    repo: '{{ gitrepos }}'
    dest: '{{ deploydest }}/pyconjp-{{ pyconyear }}-{{ item.name }}'
    force: yes
  become: True
  become_user: '{{ pyconusr }}'
  with_items: '{{ deploybranch }}'
- name: Rewrite branch setting in docker-compose.yml
  replace:
    path: '{{ deploydest }}/pyconjp-{{ pyconyear }}-{{ item.name }}/docker-compose.yml'
    regexp: '- GIT_BRANCH=master'
    replace: '- GIT_BRANCH={{ item.name }}'
  become: True
  become_user: '{{ pyconusr }}'
  with_items: '{{ deploybranch }}'
- name: Rewrite port setting in docker-compose.yml
  replace:
    path: '{{ deploydest }}/pyconjp-{{ pyconyear }}-{{ item.name }}/docker-compose.yml'
    regexp: '- "4000:4000"'
    replace: '- "{{ item.port }}:4000"'
  become: True
  become_user: '{{ pyconusr }}'
  with_items: '{{ deploybranch }}'
- name: Start web service
  shell: docker-compose up -d
  args:
    chdir: '{{ deploydest }}/pyconjp-{{ pyconyear }}-{{ item.name }}'
  become: True
  become_user: '{{ pyconusr }}'
  with_items: '{{ deploybranch }}'
- name: Copy update-web script
  copy:
    src: '{{ role_path }}/files/update-web.sh'
    dest: '{{ deploydest }}/update-web.sh'
    mode: 0755
    owner: '{{ pyconusr }}'
    group: '{{ pycongrp }}'
- name: Setup crontab
  cron:
    name: update-web
    cron_file: /etc/crontab
    minute: 15,45 
    hour: '*' 
    day: '*'
    month: '*'
    weekday: '*'
    user: '{{ pyconusr }}'
    job: '{{ deploydest }}/update-web.sh all >/dev/null 2>&1'
  with_items: '{{ deploybranch }}'
